### PR TITLE
Feathers 3 support

### PR DESCRIPTION
**Pull request by NikitaVlaznev**
A fix for:

    <rejected> Error: Callbacks are no longer supported. Use Promises or async/await instead.
    at validateArguments (/home/aquajet/projects/mfo/api/node_modules/@feathersjs/commons/lib/arguments.js:17:11)

Related issue: #36.

I've removed this line, but i'm not sure is it appropriate, but it works and tests are passing:

    args = commons.getArguments(method, args);

As Travis says, It fails to work on the old node js versions, is it necessary now?

### CODE REVIEW

**Comment by daffl** [comment]
This is great, thank you! We can drop Node 4 support but I think it would be good to still have version 6 supported (so no `async/await` unfortunately). Let me know if you need a hand with anything!

**Comment by NikitaVlaznev** [comment]
I've used babel compilation of async/await to generators, so it works on NodeJS 6 now.
NodeJS 4 is failing, could you drop this test from CI?

And @daffl, could you check whether we need to do something instead of the removed line:

    args = commons.getArguments(method, args);

There is no getArguments in commons any more.

**Comment by NikitaVlaznev** [comment]
So, @daffl, what about removing NodeJS 4 check from CI?

**Comment by daffl** [comment]
Yep, you can just remove it from the `.travis.yml` file at https://github.com/feathersjs-ecosystem/feathers-batch/blob/master/.travis.yml#L5.

Feathers core and the db adapters do not user a transpiler anymore. The big advantage is that you can install and use the repositories directly from Git. I didn't get a chance to check your PR out yet but would there be a chance to do this with promises instead of async/await?

**Comment by jcarty** [comment]
Any update on this?

Thanks!

**Comment by NikitaVlaznev** [comment]
@daffl, you can use it as git dep if you are using node >= 7.6.
If you need a node 6 we can include lib/* into the repository and update it on every release commit, it is not so bad.
It is said "API layer for modern applications" on the feathersjs.com, node 8 is the current LTS, async/await is a very important move forward, so why to downgrade the code base?)

**Comment by daffl** [comment]
You're right, I think for an ecosystem module that's totally fine. Thank you for making and updating the PR, I'll cut a new release this week.

**Comment by daffl** [comment]
Sorry for the delay. Released as v0.2.0.

Thanks a lot for doing this!

**Pull request merged**
